// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:string):Promise<main.Project>;

export function DeleteChapter(arg1:string,arg2:string):Promise<void>;

export function DeleteCharacter(arg1:string,arg2:string):Promise<void>;

export function DeleteCodexEntry(arg1:string,arg2:string):Promise<void>;

export function DeleteScene(arg1:string,arg2:string):Promise<void>;

export function EmptyTrash():Promise<void>;

export function ImportMapImage(arg1:string):Promise<string>;

export function ListChapters(arg1:string):Promise<Array<main.ChapterInfo>>;

export function ListCharacters(arg1:string):Promise<Array<string>>;

export function ListCodexEntries(arg1:string):Promise<Array<string>>;

export function ListParts(arg1:string):Promise<Array<main.ManuscriptPart>>;

export function ListScenes(arg1:string):Promise<Array<main.ChapterInfo>>;

export function ListTrash():Promise<Array<main.TrashItem>>;

export function LoadProject(arg1:string):Promise<main.Project>;

export function OpenProject():Promise<main.Project>;

export function PromoteSceneToChapter(arg1:string,arg2:string):Promise<string>;

export function ReadAtlas(arg1:string):Promise<string>;

export function ReadChapter(arg1:string,arg2:string):Promise<string>;

export function ReadCharacter(arg1:string,arg2:string):Promise<string>;

export function ReadCodexEntry(arg1:string,arg2:string):Promise<string>;

export function ReadMapImage(arg1:string,arg2:string):Promise<string>;

export function ReadOutline(arg1:string):Promise<string>;

export function ReadScene(arg1:string,arg2:string):Promise<string>;

export function ReadWorldFile(arg1:string,arg2:string):Promise<string>;

export function RestoreTrashItem(arg1:string):Promise<string>;

export function SaveProjectMeta(arg1:string,arg2:main.ProjectMeta):Promise<main.ProjectMeta>;

export function SetManuscriptOrder(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetParts(arg1:string,arg2:Array<main.ManuscriptPart>):Promise<void>;

export function WriteAtlas(arg1:string,arg2:string):Promise<void>;

export function WriteChapter(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteCharacter(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteCodexEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteOutline(arg1:string,arg2:string):Promise<void>;

export function WriteScene(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteWorldFile(arg1:string,arg2:string,arg3:string):Promise<void>;
