// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteChapter(arg1, arg2) {
  return window['go']['main']['App']['DeleteChapter'](arg1, arg2);
}

export function DeleteCharacter(arg1, arg2) {
  return window['go']['main']['App']['DeleteCharacter'](arg1, arg2);
}

export function DeleteCodexEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteCodexEntry'](arg1, arg2);
}

export function DeleteScene(arg1, arg2) {
  return window['go']['main']['App']['DeleteScene'](arg1, arg2);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function ExportManuscript(arg1, arg2) {
  return window['go']['main']['App']['ExportManuscript'](arg1, arg2);
}

export function GitClone(arg1) {
  return window['go']['main']['App']['GitClone'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitCreateRepo(arg1) {
  return window['go']['main']['App']['GitCreateRepo'](arg1);
}

export function GitHubPollLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitHubPollLogin'](arg1, arg2, arg3);
}

export function GitHubStartLogin() {
  return window['go']['main']['App']['GitHubStartLogin']();
}

export function GitInit(arg1) {
  return window['go']['main']['App']['GitInit'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['App']['GitLog'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitSetRemote(arg1, arg2) {
  return window['go']['main']['App']['GitSetRemote'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function ImportMapImage(arg1) {
  return window['go']['main']['App']['ImportMapImage'](arg1);
}

export function ImportNotesText() {
  return window['go']['main']['App']['ImportNotesText']();
}

export function ListChapters(arg1) {
  return window['go']['main']['App']['ListChapters'](arg1);
}

export function ListCharacters(arg1) {
  return window['go']['main']['App']['ListCharacters'](arg1);
}

export function ListCodexEntries(arg1) {
  return window['go']['main']['App']['ListCodexEntries'](arg1);
}

export function ListParts(arg1) {
  return window['go']['main']['App']['ListParts'](arg1);
}

export function ListScenes(arg1) {
  return window['go']['main']['App']['ListScenes'](arg1);
}

export function ListTrash() {
  return window['go']['main']['App']['ListTrash']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PromoteSceneToChapter(arg1, arg2) {
  return window['go']['main']['App']['PromoteSceneToChapter'](arg1, arg2);
}

export function ReadAtlas(arg1) {
  return window['go']['main']['App']['ReadAtlas'](arg1);
}

export function ReadChapter(arg1, arg2) {
  return window['go']['main']['App']['ReadChapter'](arg1, arg2);
}

export function ReadCharacter(arg1, arg2) {
  return window['go']['main']['App']['ReadCharacter'](arg1, arg2);
}

export function ReadCodexEntry(arg1, arg2) {
  return window['go']['main']['App']['ReadCodexEntry'](arg1, arg2);
}

export function ReadMapImage(arg1, arg2) {
  return window['go']['main']['App']['ReadMapImage'](arg1, arg2);
}

export function ReadNoteBoard(arg1) {
  return window['go']['main']['App']['ReadNoteBoard'](arg1);
}

export function ReadOutline(arg1) {
  return window['go']['main']['App']['ReadOutline'](arg1);
}

export function ReadScene(arg1, arg2) {
  return window['go']['main']['App']['ReadScene'](arg1, arg2);
}

export function ReadWorldFile(arg1, arg2) {
  return window['go']['main']['App']['ReadWorldFile'](arg1, arg2);
}

export function RestoreTrashItem(arg1) {
  return window['go']['main']['App']['RestoreTrashItem'](arg1);
}

export function SaveProjectMeta(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectMeta'](arg1, arg2);
}

export function SetManuscriptFormat(arg1, arg2) {
  return window['go']['main']['App']['SetManuscriptFormat'](arg1, arg2);
}

export function SetManuscriptOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetManuscriptOrder'](arg1, arg2, arg3);
}

export function SetParts(arg1, arg2) {
  return window['go']['main']['App']['SetParts'](arg1, arg2);
}

export function WriteAtlas(arg1, arg2) {
  return window['go']['main']['App']['WriteAtlas'](arg1, arg2);
}

export function WriteChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteChapter'](arg1, arg2, arg3);
}

export function WriteCharacter(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteCharacter'](arg1, arg2, arg3);
}

export function WriteCodexEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteCodexEntry'](arg1, arg2, arg3);
}

export function WriteNoteBoard(arg1, arg2) {
  return window['go']['main']['App']['WriteNoteBoard'](arg1, arg2);
}

export function WriteOutline(arg1, arg2) {
  return window['go']['main']['App']['WriteOutline'](arg1, arg2);
}

export function WriteScene(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteScene'](arg1, arg2, arg3);
}

export function WriteWorldFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteWorldFile'](arg1, arg2, arg3);
}
