// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:string):Promise<main.Project>;

export function ListChapters(arg1:string):Promise<Array<main.ChapterInfo>>;

export function ListCharacters(arg1:string):Promise<Array<string>>;

export function LoadProject(arg1:string):Promise<main.Project>;

export function OpenProject():Promise<main.Project>;

export function ReadChapter(arg1:string,arg2:string):Promise<string>;

export function ReadCharacter(arg1:string,arg2:string):Promise<string>;

export function ReadOutline(arg1:string):Promise<string>;

export function ReadWorldFile(arg1:string,arg2:string):Promise<string>;

export function SaveProjectMeta(arg1:string,arg2:main.ProjectMeta):Promise<main.ProjectMeta>;

export function WriteChapter(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteCharacter(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteOutline(arg1:string,arg2:string):Promise<void>;

export function WriteWorldFile(arg1:string,arg2:string,arg3:string):Promise<void>;
